version: "3.9"
services:
  http-belong-gateway:
    build: .
    restart: unless-stopped
    environment:
      - BELONG_GATEWAY_USERNAME=${BELONG_GATEWAY_USERNAME}
      - BELONG_GATEWAY_PASSWORD=${BELONG_GATEWAY_PASSWORD}